### ISSUE TITLE
Replacing to permalinks

### ISSUE THREAD

**Issue by verbossa** [gocom/rah_replace#1]
Hi,

In the main body, I have my texts truncated to a certain amount of characters. What I wanted to do is to replace the "&hellip;" at the end of the truncated texts with a "... Continue reading..." link to the article's permanent link page.

However, rah_replace plug-in does not seem to recognize this or process it as an individual article i.e. no link output is given from `<txp:permlink />` inside the plug-in.

It seems to process the code replacement outside of the `<txp:article> </txp:article>` tag. If I define the article ID in the `<txp:permlink id="1" />`, then it would finally give an output.

Here are my codes:

`<txp:rah_replace from="&hellip;" to="&hellip; <a href='<txp:permlink />'>Continue reading...</a>"><txp:rvm_substr length="1500"><txp:body /></txp:rvm_substr></txp:rah_replace>`

Is there any cunning solution to this?

Thanks for the great plug-in, by the way!

Regards,
Adi

**Comment by verbossa** [comment]
A temporary fix that I stumbled across is to re-define the article using txp:article_custom tag:

`<txp:rah_replace from="&hellip;" to="&hellip; <a href='<txp:article_custom section='articles' limit='1'><txp:permlink /></txp:article>'>Continue reading...</a>"><txp:rvm_substr length="1500"><txp:body /></txp:rvm_substr></txp:rah_replace>
`

The problem is that this only works explicitly for the very last article, not permlinks of the subsequent articles.

**Comment by gocom** [comment]
Tag attribute values are only parsed if the value is wrapped in single quotes. See [Parsing tag attributes](https://docs.textpattern.io/tags/tag-basics/parsing-tag-attributes). E.g.

```html
<txp:rah_replace from="&hellip;" to='&hellip; <a href="<txp:permlink />">Continue reading...</a>'>
  <txp:rvm_substr length="1500">
    <txp:body />
  </txp:rvm_substr>
</txp:rah_replace>
```
